output_dir: output
checkpoint_dir: ${output_dir}/checkpoints
model_id: meta-llama/Llama-3.1-8B-Instruct
model_dir: ${checkpoint_dir}/${model_id}

# Model Arguments
model:
  _component_: torchtune.models.llama3_1.llama3_1_8b

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path:  ${model_dir}/original/tokenizer.model

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: ${model_dir}
  output_dir: ${model_dir}
  checkpoint_files: [model-00001-of-00004.safetensors,model-00002-of-00004.safetensors, model-00003-of-00004.safetensors, model-00004-of-00004.safetensors]
  model_type: LLAMA3

# Environment
device: cpu
dtype: bf16
seed: 1234

# EleutherAI specific eval args
tasks: ["gsm8k"]
limit: null
max_seq_length: 256
batch_size: 8
enable_kv_cache: True

# Quantization specific args
quantizer: null

# Sampling
temperature: 0.6
top_p: 0.9
