[mypy]
python_version = 3.12
ignore_missing_imports = True
follow_imports = silent
warn_unused_ignores = False
check_untyped_defs = False
allow_redefinition = True
disable_error_code = import-untyped, no-untyped-def, var-annotated, operator, has-type, arg-type, call-arg, misc, union-attr, return-value, override, assignment, name-defined, attr-defined
exclude = ^projects/

