[project]
name = "research"
version = "0.1.0"
description = "Ed's Research monorepo."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "datasets>=2.14.4",
  "diffusers>=0.30.3",
  "einops>=0.8.0",
  "omegaconf>=2.3.0",
  "tokenizers>=0.20.1",
  "torch>=2.4.1",
  "torchao>=0.5.0",
  "torchaudio>=2.4.1",
  "torchtune>=0.3.1",
  "torchvision>=0.19.1",
  "transformers>=4.45.2",
]

[project.optional-dependencies]
dev = ["ruff", "pytest", "pytest-cov", "pytest-xdist"]
