name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Format, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: |
            uv.lock
            research/**/*.py
          python-version: "3.12"

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install dependencies
        run: |
          just install

      - name: Run Formatter
        run: |
          just fmt

      - name: Run Linter
        run: |
          just lint

      - name: Run Tests
        run: |
          just test
